export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST';
export const CREATE_ORDER_REQUEST_FAIL = 'CREATE_ORDER_REQUEST_FAIL';
export const CREATE_ORDER_REQUEST_SUCCESS = 'CREATE_ORDER_REQUEST_SUCCESS';

export const FETCH_PRODUCT_REQUEST_SUCCESS = 'FETCH_PRODUCT_REQUEST_SUCCESS';

export const FETCH_ORDER_REQUEST = 'FETCH_ORDER_REQUEST';
export const FETCH_ORDER_REQUEST_FAIL = 'FETCH_ORDER_REQUEST_FAIL';
export const FETCH_ORDER_REQUEST_SUCCESS = 'FETCH_ORDER_REQUEST_SUCCESS';

export const UPDATE_ORDER_REQUEST = 'UPDATE_ORDER_REQUEST';
export const UPDATE_ORDER_REQUEST_FAIL = 'UPDATE_ORDER_REQUEST_FAIL';
export const UPDATE_ORDER_REQUEST_SUCCESS = 'UPDATE_ORDER_REQUEST_SUCCESS';

export const DELETE_ORDER_REQUEST = 'DELETE_ORDER_REQUEST';
export const DELETE_ORDER_REQUEST_FAIL = 'DELETE_ORDER_REQUEST_FAIL';
export const DELETE_ORDER_REQUEST_SUCCESS = 'DELETE_ORDER_REQUEST_SUCCESS';
